settings:
  APP_DISPLAY_NAME: Clap
  PRODUCTION_APP_NAME: Clap
  APP_GROUP_IDENTIFIER: group.ac.clap.app
  BASE_BUNDLE_IDENTIFIER: ac.clap.app
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: "colors/accent-color"
  DEVELOPMENT_TEAM: DFDZD34G7P
