//
// Copyright 2025 Element Creations Ltd.
// Copyright 2023-2025 New Vector Ltd.
//
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial.
// Please see LICENSE files in the repository root for full details.
//

import CompoundDesignTokens
import SwiftUI

public extension Color {
    /// The colours used by Element as defined in Compound Design Tokens.
    static let compound = CompoundColors()
}

public extension ShapeStyle where Self == Color {
    /// The colours used by Element as defined in Compound Design Tokens.
    static var compound: CompoundColors { Self.compound }
}

/// The colours used by Element as defined in Compound Design Tokens.
/// This struct contains only the colour tokens in a more usable form.
@dynamicMemberLookup
public class CompoundColors {
    /// The base colour tokens that form the palette of available colours.
    ///
    /// Normally these shouldn't be necessary, however in practice we may need
    /// access for temporary tokens while waiting for official ones to be formalised.
    private static let coreTokens = CompoundCoreColorTokens.self
    /// The main semantic tokens generated from the Style Dictionary.
    private let tokens: CompoundColorTokens
    
    /// Runtime overrides for the `tokens` property (semantic tokens).
    private var tokenOverrides = [KeyPath<CompoundColorTokens, Color>: Color]()

    /// Runtime overrides for properties on `CompoundColors` itself (placeholder tokens like `_bgBubbleOutgoing`).
    private var selfOverrides = [KeyPath<CompoundColors, Color>: Color]()
    
    public subscript(dynamicMember keyPath: KeyPath<CompoundColorTokens, Color>) -> Color {
        tokenOverrides[keyPath] ?? tokens[keyPath: keyPath]
    }

    /// Customise a semantic token (`CompoundColorTokens`) at the specified key path.
    /// Supplying `nil` as the colour will remove any existing customisation.
    public func override(_ keyPath: KeyPath<CompoundColorTokens, Color>, with color: Color?) {
        tokenOverrides[keyPath] = color
    }

    /// Customise a placeholder/self token (`CompoundColors`) at the specified key path.
    /// Supplying `nil` as the colour will remove any existing customisation.
    public func override(_ keyPath: KeyPath<CompoundColors, Color>, with color: Color?) {
        selfOverrides[keyPath] = color
    }
    
    init() {
        let tokens = CompoundColorTokens()
        self.tokens = tokens
        
        decorativeColors = [
            .init(background: tokens.bgDecorative1, text: tokens.textDecorative1),
            .init(background: tokens.bgDecorative2, text: tokens.textDecorative2),
            .init(background: tokens.bgDecorative3, text: tokens.textDecorative3),
            .init(background: tokens.bgDecorative4, text: tokens.textDecorative4),
            .init(background: tokens.bgDecorative5, text: tokens.textDecorative5),
            .init(background: tokens.bgDecorative6, text: tokens.textDecorative6)
        ]
    }
    
    // MARK: - Decorative Colors

    // Used to determine the background and text colors of avatars, usernames etc.
    
    let decorativeColors: [DecorativeColor]
    
    public func decorativeColor(for contentID: String) -> DecorativeColor {
        decorativeColors[contentID.hashCode]
    }
    
    // MARK: - Awaiting Semantic Tokens
    
    // swiftformat:disable numberFormatting

    // 기본값을 별도 상수로 빼두고, computed var에서 selfOverrides를 우선 적용합니다.

    private let _borderTextFieldFocusedDefault = coreTokens.gray500
    @available(iOS, deprecated: 100000.0, message: "This token should be generated by now.")
    public var _borderTextFieldFocused: Color {
        selfOverrides[\._borderTextFieldFocused] ?? _borderTextFieldFocusedDefault
    }

    private let _bgBubbleIncomingDefault = Color(UIColor { $0.isLight ? UIColor(coreTokens.gray300) : UIColor(coreTokens.gray400) })
    @available(iOS, deprecated: 100000.0, message: "This token should be generated by now.")
    public var _bgBubbleIncoming: Color {
        selfOverrides[\._bgBubbleIncoming] ?? _bgBubbleIncomingDefault
    }

    private let _bgBubbleOutgoingDefault = Color(UIColor { $0.isLight ? UIColor(coreTokens.gray400) : UIColor(coreTokens.gray500) })
    @available(iOS, deprecated: 100000.0, message: "This token should be generated by now.")
    public var _bgBubbleOutgoing: Color {
        selfOverrides[\._bgBubbleOutgoing] ?? _bgBubbleOutgoingDefault
    }

    private let _bgCodeBlockDefault = coreTokens.gray100
    @available(iOS, deprecated: 100000.0, message: "This token should be generated by now.")
    public var _bgCodeBlock: Color {
        selfOverrides[\._bgCodeBlock] ?? _bgCodeBlockDefault
    }

    private let _borderInteractiveSecondaryAlphaDefault = coreTokens.alphaGray600
    @available(iOS, deprecated: 100000.0, message: "This token should be generated by now.")
    public var _borderInteractiveSecondaryAlpha: Color {
        selfOverrides[\._borderInteractiveSecondaryAlpha] ?? _borderInteractiveSecondaryAlphaDefault
    }

    private let _bgSubtleSecondaryAlphaDefault = coreTokens.alphaGray300
    @available(iOS, deprecated: 100000.0, message: "This token should be generated by now.")
    public var _bgSubtleSecondaryAlpha: Color {
        selfOverrides[\._bgSubtleSecondaryAlpha] ?? _bgSubtleSecondaryAlphaDefault
    }

    private let _bgCriticalSubtleAlphaDefault = coreTokens.alphaRed300
    @available(iOS, deprecated: 100000.0, message: "This token should be generated by now.")
    public var _bgCriticalSubtleAlpha: Color {
        selfOverrides[\._bgCriticalSubtleAlpha] ?? _bgCriticalSubtleAlphaDefault
    }

    private let _bgEmptyItemAlphaDefault = coreTokens.alphaGray500
    @available(iOS, deprecated: 100000.0, message: "This token should be generated by now.")
    public var _bgEmptyItemAlpha: Color {
        selfOverrides[\._bgEmptyItemAlpha] ?? _bgEmptyItemAlphaDefault
    }
    // swiftformat:enable numberFormatting
}

private extension UITraitCollection {
    /// Whether or not the trait collection contains a `userInterfaceStyle` of `.light`.
    var isLight: Bool { userInterfaceStyle == .light }
}

public struct DecorativeColor: Equatable {
    public let background: Color
    public let text: Color
}

private extension String {
    /// Calculates a numeric hash same as Element Web
    /// See original function here https://github.com/matrix-org/matrix-react-sdk/blob/321dd49db4fbe360fc2ff109ac117305c955b061/src/utils/FormattingUtils.js#L47
    var hashCode: Int {
        let characterCodeSum = reduce(0) { sum, character in
            sum + Int(character.unicodeScalars.first?.value ?? 0)
        }
        return characterCodeSum % Color.compound.decorativeColors.count
    }
}
